### ISSUE TITLE
SPI Library Documentation

### ISSUE THREAD

**Issue by michaelidesmi** [Microchip-MPLAB-Harmony/csp#30] opened 2021-06-04 07:17 UTC
I've noticed 2 minor documentation issues for the SPI Peripheral Library. I am using a PIC32MZ.

In the **SPIx_WriteRead** documentation it is stated that _It returns False if either of the size parameters are 0 and corresponding data pointer is NULL._ which is not accurate. The function will return false if both size parameters are 0.

In the **SPIx_TransferSetup** there is no mention of the fact that for the **spiSourceClock** a value of 0 will default to _Use Master Clock Frequency set in GUI_. If this is something that will become obsolete in the future ignore it.

**Comment by vishalnxt** [comment] 2021-06-21 19:39
@michaelidesmi , thank you for bringing the issues to our notice. We will update the documentation in the next release.

**Comment by vishalnxt** [comment] 2021-09-23 08:18
@michaelidesmi , the issue is fixed in v3.10 release. I am closing the ticket. Feel free to re-open it in case you find any issues.

**Closed by vishalnxt** 2021-09-23 08:18 UTC
